### PR TITLE
Added download button for exporting stats of repo in txt format

### LINKED ISSUE #85: Feat: Add a button  to download Github Stats of a repo
### Describe the feature

r1

### Add ScreenShots

c1

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by mehul-m-prajapati**
fixes #85 

https://github.com/user-attachments/assets/0d67e3d1-9f4f-4719-b5a8-1121593edaf9

### CODE REVIEW

**Comment by vansh-codes** [comment]
Can you design the downloaded file better?

**Comment by mehul-m-prajapati** [comment]
@vansh-codes : it is either csv, text or json format. Which one do you prefer?

**Comment by vansh-codes** [comment]
Cant we do it in .md ?

**Comment by mehul-m-prajapati** [comment]
Okay, let me check and do changes

**Comment by mehul-m-prajapati** [comment]
@vansh-codes : Here is updated video
https://github.com/user-attachments/assets/fa68a94e-789f-4912-a3a3-ca787c546e75

**Comment by mehul-m-prajapati** [comment]
If you have other features to implement, let me know.
I can work on it for couple of days.

**Review by vansh-codes — APPROVED** [review]

**Pull request merged**
