### PR TITLE
Added a navigation button to profile Page

### PR DESCRIPTION
**Pull request by Akshithsaai**
Fixes : #93

### CODE REVIEW

**Review by vansh-codes — APPROVED** [review]

**Comment by vansh-codes** [comment]
@Akshithsaai 

https://docs.google.com/forms/d/e/1FAIpQLSdnqJ5crpQFQEQXGTzekfKUxOJCXkSx8AykqvvHzlqBcNGMAQ/viewform

Nominate me if you liked my work and management

**Comment by Akshithsaai** [comment]
Ok @vansh-codes 👍🏻. 
Thanks for giving me the opportunity to contribute. 
I look forward to collaborate on any projects in future. 
Reach me at akshithsaaimanchikanti@gmail.com

**Comment by vansh-codes** [comment]
Sure @Akshithsaai 

What about the image generation functionality, are you working on it? can you complete that?

**Comment by Akshithsaai** [comment]
Yeah I have read the api docs and I can show card showing those stats. 

Should I generate an image having these stats or is it sufficient if I show them as info in a card? 

@vansh-codes

**Comment by vansh-codes** [comment]
show it as stats only, just I need the basic setup, then later modification can be done

**Pull request merged**
