### PR TITLE
issue 6 Added text animation 

### PR DESCRIPTION
**Pull request by gurliv21**
Closes: #6

https://github.com/user-attachments/assets/a838c32c-d84a-40dc-a2bb-6f4a22f3e2c7

### CODE REVIEW

**Comment by vansh-codes** [comment]
Why did you change the background, please make the background as it was earlier

**Comment by vansh-codes** [comment]
Can you list all the changes you have made in the code as I can see alot of changes
list all the changes in all files that you did
I can see 8 files changed for this

**Comment by gurliv21** [comment]
Specifically, I made changes to Home.jsx by adding a TypingAnimation component with the following code:
<TypingAnimation
  duration={80}
  className="text-4xl font-light text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-pink-600 tracking-widest mb-8"
  text="Let's, Begin..."
/>
The other modified files were likely added as a result of downloading the TypingAnimation from MagicUI as you can see in typing-animation.jsx in components/ui

**Comment by vansh-codes** [comment]
Resolve merge conflicts @gurliv21

**Comment by vansh-codes** [comment]
@gurliv21  Resolve the merge conflicts to get the PR merged

**Pull request closed without merging**
