### PR TITLE
Implement GitHub PR Issue Checker Workflow

### PR DESCRIPTION
**Pull request by smog-root**
Closes: #45 

**Usage:**

1. When a pull request is created or edited, the workflow automatically triggers.

2. The workflow checks for:
- A non-empty PR description.
- A valid issue reference format (`FIX #<issue-number>` or `Fixes, or Closes #NEW`).
3. If either check fails, the PR will be marked as failing, and the author will receive clear error messages in the PR comments.
4. If all checks pass, a confirmation message will indicate that the PR is valid.

**_Note_**: Kindly add all the labels added to the issue, to this PR!

@vansh-codes

### CODE REVIEW

**Comment by smog-root** [comment]
Can you please upgrade it to level2 ? @vansh-codes

**Comment by vansh-codes** [comment]
Do the same modification here as I suggested in different repo/project

**Comment by vansh-codes** [comment]
Change the word `FIX` in the description to `FIXES`

**Review by vansh-codes — APPROVED** [review]

**Comment by smog-root** [comment]
can you make this one level2?? the other one is duplicated!! @vansh-codes

**Comment by smog-root** [comment]
please make it level2 please 😞

**Comment by vansh-codes** [comment]
Sorry buddy! 57 lines of code cant be assigned level 2

**Comment by vansh-codes** [comment]
> Change the word `FIX` in the description to `FIXES`

Do this change asap

**Comment by smog-root** [comment]
> > Change the word `FIX` in the description to `FIXES`
> 
> Do this change asap

Done!

**Comment by smog-root** [comment]
Done! merge it! @vansh-codes

**Pull request merged**
