### PR TITLE
fix: 🐛 Enhanced README with contributors section

### PR DESCRIPTION
**Pull request by yashksaini-coder**
✅ Closes: #5

This PR includes changes that involves integrating a dynamic URL to showcase stargazers & forkers in the project. 

- Stargazers
image

- Forkers
image

It also includes an action workflow that fetches the contributors profiles and display in the contributors section in the Footer area. 

******************************************************************
### Documentation Improvements:

* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L1-R36): Reformatted the project title and introduction for better readability and added a table to display project statistics.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L38-R86): Enhanced the "How it works" section with bold headings and better formatting for parameters and example URLs.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L124-R177): Added a new "Contributors" section to acknowledge contributors and included dynamic badges for stargazers and forkers.

### Automation:

* [`.github/workflows/add-contributors.yml`](diffhunk://#diff-4387a200be2fa409ad73ee2bf23884b607b1bc00d1b366aed9348b8726557423R1-R26): Added a GitHub Actions workflow to automatically update the contributors list in the README file.

[Gityzer-5.webm](https://github.com/user-attachments/assets/0dd83a9e-96f0-4adc-b3d4-bb04bcc3c909)

******************************************************************

@vansh-codes Can you review this PR and add labels to it `gssoc-ext`, `hacktoberfest`, `hacktoberfest-accepted`.

### CODE REVIEW

**Comment by vansh-codes** [comment]
Please update the contributors dynamic update to be in a new file named CONTRIBUTORS.md and not in README.md
I told this in your issue also
Create a new file and all the contributors should be listed there along with their usernames
Do this update

**Comment by yashksaini-coder** [comment]
@vansh-codes no worries, I will update them the files and commit changes as per your requests

**Review by vansh-codes — CHANGES_REQUESTED** [review]
Why the workflow has your details??

image

**Comment by yashksaini-coder** [comment]
@vansh-codes will this email work "vanshchaurasiya1557@gmail.com", it is your github registered email right

**Comment by yashksaini-coder** [comment]
### Update the commit details:-

image

**Review by vansh-codes — APPROVED** [review]
Good job!

**Comment by vansh-codes** [comment]
@yashksaini-coder 
Contributors are not updating in CONTRIBUTORS.md
image

The default branch is master in this repo, is this the reason its not working?

**Comment by vansh-codes** [comment]
image

See this @yashksaini-coder

**Comment by vansh-codes** [comment]
I had to make it run manually then it worked!

**Comment by Hemu21** [comment]
@vansh-codes  if it fine please add relevant level label

**Comment by yashksaini-coder** [comment]
> @vansh-codes if it fine please add relevant level label

thx @Hemu21 i forgot about this PR level

**Pull request merged**
