### PR TITLE
issue 19 resolved. tagline generation using gemini successfully added.

### LINKED ISSUE #19: Feat: Setup AI model to begin AI integrity ⚙️
### Describe the feature

As described in the [README](https://github.com/vansh-codes/Gityzer/README.md), its time to start working on AI to take GITYZER a step ahead and start focusing on what matters
Set up AI in this repository following best practices & folder structure
Anyone who does this task effectively will be rewarded `level3` 🎊 
Initial setup includes:
- setting up AI folder to start working with GEMINI API
- on going to `/<username>`, a unique random tagline should be generated by the Gemini AI

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by garimabhayanaa**
Fixes #19 
This pull request adds tagline generation using gemini, initiating ai integration.

### CODE REVIEW

**Review by vansh-codes — CHANGES_REQUESTED** [review]
Changes expected:
1. in the next page where Welcome, <username> is displayed, the AI generated msg should be displayed there as text for now
2. create a new file for backend `src/app/api/ai/route.js` and update the AI modifications in that file and revert the changes in `api/user/route.js`

**Comment by vansh-codes** [comment]
Can you share a screenshot or video which shows the working??

**Comment by garimabhayanaa** [comment]
> Can you share a screenshot or video which shows the working??

Due to some issue with my local development environment, i cannot provide a screenshot. I’m actively troubleshooting it, but if needed, I can provide detailed steps on the changes I’ve made

**Comment by vansh-codes** [comment]
Does your code needs GEMINI API key to run??

**Comment by garimabhayanaa** [comment]
> Does your code needs GEMINI API key to run??

yes

**Comment by vansh-codes** [comment]
Update it in the `.env.example` so I can enter my api key and use it

**Comment by vansh-codes** [comment]
Do this asap and commit so I can merge it

**Comment by vansh-codes** [comment]
Also whats the status of #20 ??

**Comment by garimabhayanaa** [comment]
> Update it in the `.env.example` so I can enter my api key and use it

updating code

**Review by vansh-codes — APPROVED** [review]
Looks good!

**Comment by garimabhayanaa** [comment]
> Also whats the status of #20 ??

In process, Will be completed before an hour.

**Comment by vansh-codes** [comment]
Its not working 🥲

**Comment by garimabhayanaa** [comment]
> Its not working 🥲

What is the error?

**Comment by vansh-codes** [comment]
Check its not working!
https://gityzer.vercel.app/

**Comment by garimabhayanaa** [comment]
I have made some changes too, in the .env.example and ai/route.js, let me know if that helps.

**Comment by vansh-codes** [comment]
Push those changes in new PR asap

**Pull request merged**
