### PR TITLE
Added dynamic UI and transitions to home page(#16 issue)

### PR DESCRIPTION
**Pull request by 770navyasharma**
Revamped the UI with better transitions and effects like ripple and others

https://github.com/user-attachments/assets/dc828a17-ac47-426c-8062-f7d3ae2b773f

### CODE REVIEW

**Comment by vansh-codes** [comment]
Your issue #16 says something else and the work you did is something else!
Can you please explain or shall we close the issue and PR ?

**Comment by vansh-codes** [comment]
You had to create a new page `Who are we` right?

**Comment by 770navyasharma** [comment]
> You had to create a new page `Who are we` right?

Yess I have to make. Currently I made the UI better as said and that page I am doing.

**Comment by vansh-codes** [comment]
> > You had to create a new page `Who are we` right?
> 
> Yess I have to make. Currently I made the UI better as said and that page I am doing.

No no, we dont need any modification in the first page, you can revert those changes, just make a new `Who are we` page as shown in the screenshots by you and follow the same theme as it is on website

**Pull request closed without merging**
