### PR TITLE
Automation of project structure updation using GitHub workflows and Python scripts

### LINKED ISSUE #71: Doc Update: Automation of project structure updation using GitHub workflows and Python scripts
### Describe your chaotic idea

Currently, the project doesn't have a project structure. And, it would be a bit difficult for newcomers to understand the project and how to add more chaos to it's existing structure completely. Also, it's difficult for anyone to manually change the project structure as it grows in size day by day. So, automating this with GitHub workflows and Python script will make the maintenance easier and enhance organised chaos(metaphor!).

I want to add a detailed project structure in a separate file(redirect in README.md) for the contributors to refer to and automate its updation process as new files are added in the projects. This will help them refer to the structure and will make it easier for them to understand the structure and spread more chaos to the project. Also, it's difficult for anyone to manually change the project structure as it grows in size day by day. So, automating this with GitHub workflows and a Python script will make the project more accessible to the Contributors and spread more chaos.

### Add Screenshots or Sketches

Sample of how the workflow would be automated and the project structure after updation in readme:
image

image

### Confirm

- [X] I agree to follow this project's Code of Conduct
- [X] I'm GSSOC'24 Extd registered Contributor
- [X] I'm Hacktoberfest registered Contributor
- [X] I want to work on this documentation issue

### PR DESCRIPTION
**Pull request by rajdeepchakraborty-rc**
# Issue Resolved:

- Closes #71 

# Description
The project did not have a project structure, which would make it difficult for the newcomers to understand the project structure better. 
I have added a **detailed project structure**(redirect in README.md) in a **separate file**(since the project structure is very long and would make the README file too long making it less readable to the users) for the contributors to refer to and also **automated its updation process** as new files are added in the projects. 

**NOTE:** Every time any changes are pushed into the **master** branch, the workflow will run and then update the structure(if any changes).

This will help the contributors refer to the structure and will make it easier for them to understand where to contribute.
Also, it's difficult for anyone to manually change the project structure as it grows in size day by day. So, automating this with **GitHub workflows** and **Python script** will make the maintenance easier and help you focus on reviewing PR and assigning issues.

# Screenshots

- Redirect:
image

- Project structure: 
image
image

### CODE REVIEW

**Review by vansh-codes — APPROVED** [review]
Good job!

**Comment by vansh-codes** [comment]
Brother documentation and workflows are supposed to be level1, because you worked hard on it and created on your own, I have you level3 for the previous PR, for this repo you would have copy pasted the code with minor changes, so I guess level1 is good for this

**Comment by rajdeepchakraborty-rc** [comment]
> Brother documentation and workflows are supposed to be level1, because you worked hard on it and created on your own, I have you level3 for the previous PR, for this repo you would have copy pasted the code with minor changes, so I guess level1 is good for this

Sure. Thanks for reviewing the PR! Hope you have a great day ahead!

**Comment by vansh-codes** [comment]
Hii @rajdeepchakraborty-rc 

I encountered this error for the workflow

Screenshot 2024-11-06 222728

Can you please look into this issue and fix it?
Do create a new issue, i will assign it to you with level1

**Comment by rajdeepchakraborty-rc** [comment]
@vansh-codes Sure I will look into it.

**Pull request merged**
